-- Load config files
require("remap")
require("set")
require("plugins_install")

require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/colors")
require("plugins/telescope")
require("plugins/lsp")
require("plugins/comment")
require("plugins/leap")
require("plugins/lualine")
require("plugins/gitsigns")
require("plugins/undotree")
require("plugins/nvim-cursorline")
require("plugins/cscope_maps")
require("plugins/mini_pairs")
-- require("plugins/mini_files")
-- require("plugins/carbon")
